---
name: authentik-ci-main-daily

on:
  workflow_dispatch:
  schedule:
    # Every night at 3am
    - cron: "0 3 * * *"

jobs:
  test-container:
    name: Test Container ${{ matrix.version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version:
          - docs
          - version-2025-2
          - version-2024-12
    steps:
      - uses: actions/checkout@v4
        name: ${{ matrix.version }} Setup
      - run: |
          current="$(pwd)"
          dir="/tmp/authentik/${{ matrix.version }}"
          mkdir -p $dir
          cd $dir
          wget https://${{ matrix.version }}.goauthentik.io/docker-compose.yml
          ${current}/scripts/test_docker.sh
