name: CI Web UI

on:
  push:
    branches:
      - main
      - next
      - version-*
  pull_request:
    branches:
      - main
      - version-*

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: "npm"
          cache-dependency-path: package-lock.json
      - name: Install Node.js dependencies
        run: npm ci
      - name: Generate TypeScript API
        run: make gen-client-ts
      - name: Build
        run: |
          npm run build -w @goauthentik/web
      - name: Type check
        run: |
          npm run typecheck
      - name: Lint
        run: |
          npm run lint -w @goauthentik/web
          npm run lint:lockfile -w @goauthentik/web
          npm run lit-analyse -w @goauthentik/web
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: "npm"
          cache-dependency-path: package-lock.json
      - name: Install Node.js dependencies
        run: npm ci
      - name: Generate TypeScript API
        run: make gen-client-ts
      - name: build
        run: |
          npm run build -w @goauthentik/web
          npm run typecheck
  ci-web-mark:
    name: CI Web Mark
    if: always()
    needs:
      - build
      - lint
    runs-on: ubuntu-latest
    steps:
      - uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
  test:
    name: Test
    needs:
      - ci-web-mark
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: "npm"
          cache-dependency-path: package-lock.json
      - name: Install Node.js dependencies
        run: npm ci
      - name: Generate TypeScript API
        run: make gen-client-ts
      - name: Test Web UI
        run: npm run test -w @goauthentik/web || exit 0
