name: CI Docs Website

on:
  push:
    branches:
      - main
      - next
      - version-*
  pull_request:
    branches:
      - main
      - version-*

jobs:
  lint:
    name: "Lint"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: "npm"
          cache-dependency-path: package-lock.json
      - name: Install Node.js dependencies
        run: |
          npm ci
      - name: Generate TypeScript API
        run: make gen-client-ts
      - name: Lint Docs
        run: |
          npm run lint:prettier:check
          npm run lint:lockfile -w @goauthentik/docs
  test:
    name: "Test Docs"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: "npm"
          cache-dependency-path: package-lock.json
      - name: Install Node.js dependencies
        run: |
          npm ci
      - name: Generate TypeScript API
        run: make gen-client-ts
      - name: Test Docs
        run: |
          npm run test -w @goauthentik/docs
  build:
    name: "Build Docs"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: "npm"
          cache-dependency-path: package-lock.json
      - name: Install Node.js dependencies
        run: npm ci
      - name: Build
        run: |
          npm run build -w @goauthentik/docs
  ci-website-mark:
    name: "CI Website Mark"
    if: always()
    needs:
      - lint
      - test
      - build
    runs-on: ubuntu-latest
    steps:
      - uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
